### ISSUE TITLE
how is this better than Polymer/lazy-imports ?

### ISSUE THREAD

**Issue by cordovapolymer** [seaneking/lazy-import#1]
how is this better than Polymer/lazy-imports ?
Does it support polymer build, i mean do the files specified by lazy-import are put into the bundles?

**Comment by madeleineostoja** [comment]
Polymer's lazy-imports is pretty cumbersome for what it does, this is meant to just be an super simple way to declaratively import a component - eg to make iron-pages lazy without any real effort. If you want something more powerful, can always do something custom (with importHref / lazy-imports / DIY).

Don't know the internals of polymer build, but if you're referring to vulcanize (ie: import inlining), then no, because vulcanize just reads HTML import links and inlines them. This creates import links on the fly when you go active.

**Comment by cordovapolymer** [comment]
@seaneking I'm talking about polymer [build from polymer-cli ](https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build), it's evolved from legacy gulp build with vulcanize.
There must be a way to make your imports readable by polymer-bundler, otherwise it's quite useless.

**Comment by madeleineostoja** [comment]
That page you linked describes an option called  `includeDependencies` for exactly this use-case (defining extra dynamically-imported deps to bundle).

In any case don't see how not bundling lazy import deps make it 'useless'. If you're serving over HTTP/2, for example, then bundling deps with polymer-build is an antipattern anyway.

**Comment by cordovapolymer** [comment]
The issue is that polymer polymer build should see declared imports just to copy bower_components to the bundle, it doesn't concatenate them to one file, it's not an antipattern.

**Comment by madeleineostoja** [comment]
Ah okay, my mistake. Thought you were talking about vulcanising
